
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ANIL BARBARE
 */
public class Admin extends Global {
    public void jdbc()
{
    try
        {
            Class.forName("java.sql.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/lbms?useSSL=false","root","1234");
            stmt=con.createStatement();          
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error: "+e.getMessage());           
        }
}

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        invbtn = new javax.swing.JButton();
        booksbtn = new javax.swing.JButton();
        membtn = new javax.swing.JButton();
        orderbtn = new javax.swing.JButton();
        summbtn = new javax.swing.JButton();
        settbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Admin Home");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, -1, -1));

        invbtn.setBackground(new java.awt.Color(255, 255, 255));
        invbtn.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        invbtn.setForeground(new java.awt.Color(255, 255, 255));
        invbtn.setText(" INVENTORY");
        invbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        invbtn.setContentAreaFilled(false);
        invbtn.setNextFocusableComponent(booksbtn);
        invbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invbtnActionPerformed(evt);
            }
        });
        getContentPane().add(invbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 200, 150));

        booksbtn.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        booksbtn.setForeground(new java.awt.Color(255, 255, 255));
        booksbtn.setText("<html>\n<center>MANAGE</center>\n<br><center>BOOKS</center>");
        booksbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        booksbtn.setContentAreaFilled(false);
        booksbtn.setNextFocusableComponent(membtn);
        booksbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booksbtnActionPerformed(evt);
            }
        });
        getContentPane().add(booksbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, 200, 150));

        membtn.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        membtn.setForeground(new java.awt.Color(255, 255, 255));
        membtn.setText("MEMBERS");
        membtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        membtn.setContentAreaFilled(false);
        membtn.setNextFocusableComponent(summbtn);
        membtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                membtnActionPerformed(evt);
            }
        });
        getContentPane().add(membtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 190, 190, 150));

        orderbtn.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        orderbtn.setForeground(new java.awt.Color(255, 255, 255));
        orderbtn.setText("ORDERS");
        orderbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        orderbtn.setContentAreaFilled(false);
        orderbtn.setNextFocusableComponent(settbtn);
        orderbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderbtnActionPerformed(evt);
            }
        });
        getContentPane().add(orderbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 430, 200, 150));

        summbtn.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        summbtn.setForeground(new java.awt.Color(255, 255, 255));
        summbtn.setText("<HTML>\n<CENTER>WEEKLY</CENTER>\n<BR>\n<CENTER>SUMMARY</CENTER>");
        summbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        summbtn.setContentAreaFilled(false);
        summbtn.setNextFocusableComponent(orderbtn);
        summbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                summbtnActionPerformed(evt);
            }
        });
        getContentPane().add(summbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 200, 150));

        settbtn.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        settbtn.setForeground(new java.awt.Color(255, 255, 255));
        settbtn.setText(" SETTINGS");
        settbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        settbtn.setContentAreaFilled(false);
        settbtn.setNextFocusableComponent(invbtn);
        settbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settbtnActionPerformed(evt);
            }
        });
        getContentPane().add(settbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 430, 190, 150));

        jButton1.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jButton1.setText("LOGOUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 70, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/default_profile.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 160, 160));

        user.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 16)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setToolTipText("");
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 160, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/library.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void invbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invbtnActionPerformed
new Inventory().setVisible(true);
this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_invbtnActionPerformed

    private void settbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settbtnActionPerformed
new AdminSettings().setVisible(true);
this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_settbtnActionPerformed

    private void booksbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booksbtnActionPerformed
new Manage_Books().setVisible(true);
this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_booksbtnActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
invbtn.requestFocus();
jdbc();
try
{
    String sql="select name from admin where username='"+Login.adname.getText()+"';";
    //System.out.println(sql);
    rs=stmt.executeQuery(sql);
    rs.next();
    String name=rs.getString(1);
    user.setText("<html><body>"+name);
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(this, "Error: "+e.getMessage());
}
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
logout();
new Login().setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void orderbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderbtnActionPerformed
new Orders().setVisible(true);
this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_orderbtnActionPerformed

    private void summbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_summbtnActionPerformed
new Weekly_Summary().setVisible(true);
this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_summbtnActionPerformed

    private void membtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_membtnActionPerformed

        new MembersList().setVisible(true);
this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_membtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton booksbtn;
    private javax.swing.JButton invbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton membtn;
    private javax.swing.JButton orderbtn;
    private javax.swing.JButton settbtn;
    private javax.swing.JButton summbtn;
    public static javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
