
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ANIL BARBARE
 */
public class Edit_Member extends Global {
    String oldnm="";
 public void jdbc()
{
    try
        {
            Class.forName("java.sql.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/lbms","root","1234");
            stmt=con.createStatement();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error: "+e.getMessage());           
        }
}
    /**
     * Creates new form Edit_Member
     */
    public Edit_Member() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        m = new javax.swing.JRadioButton();
        f = new javax.swing.JRadioButton();
        o = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        email = new javax.swing.JTextField();
        contact2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addresstxt = new javax.swing.JTextArea();
        memtype = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 770));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Edit Member Details");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, -1, -1));

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Name");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 60, -1));

        nametxt.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 16)); // NOI18N
        nametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametxtActionPerformed(evt);
            }
        });
        jPanel3.add(nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 280, 30));

        age.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 16)); // NOI18N
        jPanel3.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 280, 30));

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gender");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, -1, -1));

        buttonGroup1.add(m);
        m.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 16)); // NOI18N
        m.setForeground(new java.awt.Color(255, 255, 255));
        m.setText("Male");
        m.setOpaque(false);
        jPanel3.add(m, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, -1, -1));

        buttonGroup1.add(f);
        f.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 16)); // NOI18N
        f.setForeground(new java.awt.Color(255, 255, 255));
        f.setText("Female");
        f.setOpaque(false);
        jPanel3.add(f, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, 90, -1));

        buttonGroup1.add(o);
        o.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 16)); // NOI18N
        o.setForeground(new java.awt.Color(255, 255, 255));
        o.setText("Other");
        o.setOpaque(false);
        jPanel3.add(o, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 490, -1, -1));

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Age");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        jButton3.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 550, -1, -1));

        email.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 16)); // NOI18N
        jPanel3.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 280, 30));

        contact2.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 16)); // NOI18N
        jPanel3.add(contact2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 280, 30));

        addresstxt.setColumns(20);
        addresstxt.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 16)); // NOI18N
        addresstxt.setRows(5);
        jScrollPane1.setViewportView(addresstxt);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 280, 70));

        memtype.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        memtype.setMaximumRowCount(4);
        memtype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "JRR Tolkien Platinum ", "Dan Brown Gold", "Agatha Christie Silver", "JK Rowling Bronze" }));
        memtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memtypeActionPerformed(evt);
            }
        });
        jPanel3.add(memtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 410, 270, 40));

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Contact No");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Address");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Membership Type");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, 40));

        jButton6.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jButton6.setText("SAVE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 550, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "JRR Tolkien Platinum", "Dan Brown Gold", "Agatha Christie Silver", "JK Rowling Bronze" }));
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 280, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 610, 620));

        jButton4.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/home.png"))); // NOI18N
        jButton4.setText("HOME");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jButton5.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/logout.png"))); // NOI18N
        jButton5.setText("LOGOUT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/library.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(24235345, 23413144));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 770));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new Admin().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        logout();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void memtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memtypeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 new MembersList().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void nametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametxtActionPerformed
jdbc();
try
{
    oldnm = nametxt.getText();
            String sql = "Select * from member where membername = '"+oldnm+"';";
            ResultSet rs = stmt.executeQuery(sql);
            if(rs.next())
            {
                age.setText(rs.getString("age"));
                contact2.setText(rs.getString("contact"));
                addresstxt.setText(rs.getString("address"));
                jComboBox1.setSelectedItem(rs.getString("membership"));
                email.setText(rs.getString("email"));
                String gen = rs.getString("gender");
                switch (gen) {
                    case "M":
                        m.setSelected(true);
                        break;
                    case "F":
                        f.setSelected(true);
                        break;
                    case "O":
                        o.setSelected(true);
                        break;
                    default:
                        break;
                }
                String membtype = rs.getString("membership");
                switch (membtype) {
                    case "P":
                        jComboBox1.setSelectedIndex(0);
                        break;
                    case "G":
                        jComboBox1.setSelectedIndex(1);
                        break;
                    case "S":
                        jComboBox1.setSelectedIndex(2);
                        break;
                    case "B":
                        jComboBox1.setSelectedIndex(3);
                        break;    
                    default:
                        break;
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "No member found");
            }
rs.close();
stmt.close();
con.close();
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e.getMessage());
}
    }//GEN-LAST:event_nametxtActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
jdbc();

int type=jComboBox1.getSelectedIndex();
String mem_type=null;
switch(type)
{
    case 0: mem_type="P";
    break;
    case 1: mem_type="G";
    break;
    case 2: mem_type="S";
    break;
    case 3: mem_type="B";
    break;
}
String gen=null;
if(m.isSelected())
    gen="M";
else if(f.isSelected())
    gen="F";
else if(o.isSelected())
    gen="O";
else
    JOptionPane.showMessageDialog(null, "Please select a gender.");  
switch(gen)
{
    case "O":
    case "M":
    case "F":
        try
        {
            String sql="update member set membername='"+nametxt.getText()+"',age='"+age.getText()+"',contact='"+contact2.getText()+"',address='"+addresstxt.getText()+"',email='"+email.getText()+"',gender='"+gen+"',membership='"+mem_type+"' where membername='"+oldnm+"';";
int a=stmt.executeUpdate(sql);
if(a!=0)
JOptionPane.showMessageDialog(null,"Successfully updated data");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    default :
        nametxt.setText("");
       age.setText("");
contact2.setText("");
addresstxt.setText("");
email.setText("");
age.setText("");
m.setSelected(false);
f.setSelected(false);
o.setSelected(false);break;
    
}




        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
nametxt.setText("");
age.setText("");
contact2.setText("");
addresstxt.setText("");
email.setText("");
age.setText("");
m.setSelected(false);
f.setSelected(false);
o.setSelected(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit_Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit_Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit_Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit_Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit_Member().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addresstxt;
    private javax.swing.JTextField age;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField contact2;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton f;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton m;
    private javax.swing.JComboBox memtype;
    private javax.swing.JTextField nametxt;
    private javax.swing.JRadioButton o;
    // End of variables declaration//GEN-END:variables
}
