import java.sql.*;
import javax.swing.*;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Login.java
 *
 * Created on Oct 9, 2018, 10:00:24 AM
 */

/**
 *
 * @author DAV
 */
public class Login extends Global {
    public void jdbc()
{
    try
        {
            Class.forName("java.sql.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/lbms?useSSL=false","root","1234");
            stmt=con.createStatement();          
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error: "+e.getMessage());           
        }
}
    
    

    /** Creates new form Login */
    public Login() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        adminlogin = new javax.swing.JButton();
        adname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        adminpass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        mname = new javax.swing.JTextField();
        memlogin = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        memregstr = new javax.swing.JButton();
        mempass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/admin.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ADMIN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Courier New", 1, 36), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 240, 270));

        adminlogin.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        adminlogin.setText("LOGIN");
        adminlogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        adminlogin.setNextFocusableComponent(adname);
        adminlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminloginActionPerformed(evt);
            }
        });
        getContentPane().add(adminlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 540, 150, 50));

        adname.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 16)); // NOI18N
        adname.setNextFocusableComponent(adminpass);
        getContentPane().add(adname, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, 210, 30));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, -1, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 490, 110, -1));

        adminpass.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 16)); // NOI18N
        adminpass.setNextFocusableComponent(adminlogin);
        getContentPane().add(adminpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 490, 210, 30));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/user.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MEMBER", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Courier New", 1, 36), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 140, 240, 270));

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Username :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 430, 130, 40));

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Password :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 490, -1, -1));

        mname.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 16)); // NOI18N
        mname.setNextFocusableComponent(mempass);
        mname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnameActionPerformed(evt);
            }
        });
        getContentPane().add(mname, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 440, 220, 30));

        memlogin.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        memlogin.setText("LOGIN");
        memlogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        memlogin.setNextFocusableComponent(memregstr);
        memlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memloginActionPerformed(evt);
            }
        });
        getContentPane().add(memlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 550, 140, 50));

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Don't have a account ? Register ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 620, 320, 40));

        memregstr.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        memregstr.setText("REGISTER");
        memregstr.setNextFocusableComponent(mname);
        memregstr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memregstrActionPerformed(evt);
            }
        });
        getContentPane().add(memregstr, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 610, 170, 50));

        mempass.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 16)); // NOI18N
        mempass.setNextFocusableComponent(memlogin);
        getContentPane().add(mempass, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 490, 220, 30));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/library.jpg"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
/*jdbc();
        try
 {
    String sql="select * from admin;";
    rs=stmt.executeQuery(sql);
    while(rs.next())
    {
        String a=adminuname.getText();
        String b=new String(adminpass.getPassword());
        if(a.equals(rs.getString(1)) && b.equals(rs.getString(2)));
        
    }
 }
catch(Exception e)
 {
     JOptionPane.showMessageDialog(null, e.getMessage());
 }*/
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void adminloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminloginActionPerformed
jdbc();
try
 {    
    String sql="select * from admin where username='"+adname.getText()+"' and pass='"+new String(adminpass.getPassword())+"';";
    rs=stmt.executeQuery(sql);
    if(rs.next())
    {
       new Admin().setVisible(true);
       this.dispose(); 
    }
    else
    {
     JOptionPane.showMessageDialog(null,"Please enter correct username/password");   
    }
 }
catch(Exception e)
 {
     JOptionPane.showMessageDialog(null, e.getMessage());
 }
        // TODO add your handling code here:
    }//GEN-LAST:event_adminloginActionPerformed

    private void mnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnameActionPerformed

    private void memregstrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memregstrActionPerformed
new Register().setVisible(true);
this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_memregstrActionPerformed

    private void memloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memloginActionPerformed
jdbc();
try
 {
    String sql="select * from member where username='"+mname.getText()+"' and pass='"+new String(mempass.getPassword())+"';";
    rs=stmt.executeQuery(sql);
    if(rs.next())
    {
       new Member().setVisible(true);
       this.dispose(); 
    }
    else
    {
     JOptionPane.showMessageDialog(null,"Please enter correct username/password");   
    }
 }
catch(Exception e)
 {
     JOptionPane.showMessageDialog(null, e.getMessage());
 }
        // TODO add your handling code here:
    }//GEN-LAST:event_memloginActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton adminlogin;
    private javax.swing.JPasswordField adminpass;
    public static javax.swing.JTextField adname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton memlogin;
    private javax.swing.JPasswordField mempass;
    private javax.swing.JButton memregstr;
    public static javax.swing.JTextField mname;
    // End of variables declaration//GEN-END:variables

}
