
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ravik
 */
public class MemberSettings extends Global {
    public void jdbc()
{
    try
        {
            Class.forName("java.sql.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/lbms?useSSL=false","root","1234");
            stmt=con.createStatement();          
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error: "+e.getMessage());           
        }
}

    /**
     * Creates new form MemberSettings
     */
    public MemberSettings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        newname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        newpass = new javax.swing.JPasswordField();
        confpass = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        m = new javax.swing.JRadioButton();
        f = new javax.swing.JRadioButton();
        o = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        contact = new javax.swing.JTextField();
        edit = new javax.swing.JButton();
        conf = new javax.swing.JButton();
        mem_type = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addresstxt = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 770));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Member Settings");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Change Login Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Courier New", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("New Username");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        newname.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 16)); // NOI18N
        newname.setNextFocusableComponent(newpass);
        jPanel2.add(newname, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 170, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("New Password");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Confirm Password");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jButton2.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jButton2.setText("CONFIRM");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        newpass.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 16)); // NOI18N
        jPanel2.add(newpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 170, 30));

        confpass.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 16)); // NOI18N
        jPanel2.add(confpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 170, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 480, 360));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Personal Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Courier New", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Name");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 60, -1));

        nametxt.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 16)); // NOI18N
        nametxt.setNextFocusableComponent(email);
        jPanel3.add(nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 280, 30));

        email.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 16)); // NOI18N
        email.setNextFocusableComponent(m);
        jPanel3.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 280, 30));

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gender");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 80, -1));

        buttonGroup1.add(m);
        m.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 16)); // NOI18N
        m.setForeground(new java.awt.Color(255, 255, 255));
        m.setText("Male");
        m.setNextFocusableComponent(f);
        m.setOpaque(false);
        jPanel3.add(m, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        buttonGroup1.add(f);
        f.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 16)); // NOI18N
        f.setForeground(new java.awt.Color(255, 255, 255));
        f.setText("Female");
        f.setNextFocusableComponent(o);
        f.setOpaque(false);
        jPanel3.add(f, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 90, -1));

        buttonGroup1.add(o);
        o.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 16)); // NOI18N
        o.setForeground(new java.awt.Color(255, 255, 255));
        o.setText("Other");
        o.setNextFocusableComponent(contact);
        o.setOpaque(false);
        jPanel3.add(o, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, -1, -1));

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Contact");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, 30));

        contact.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 16)); // NOI18N
        jPanel3.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 280, 30));

        edit.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        edit.setText("EDIT");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel3.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, -1, -1));

        conf.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        conf.setText("CONFIRM");
        conf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confActionPerformed(evt);
            }
        });
        jPanel3.add(conf, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, -1, -1));

        mem_type.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        mem_type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "JRR Tolkien Platinum", "Dan Brown Gold", "Agatha Christie Silver", "JK Rowling Bronze" }));
        jPanel3.add(mem_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 280, 40));

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Membership Type");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, 40));

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Address");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        addresstxt.setColumns(20);
        addresstxt.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 16)); // NOI18N
        addresstxt.setRows(5);
        jScrollPane1.setViewportView(addresstxt);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 280, 70));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 160, 580, 580));

        jButton4.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/home.png"))); // NOI18N
        jButton4.setText("HOME");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jButton5.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/logout.png"))); // NOI18N
        jButton5.setText("LOGOUT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/library.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(24235345, 23413144));
        jLabel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jLabel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
nametxt.setEnabled(false);
email.setEnabled(false);
m.setEnabled(false);
f.setEnabled(false);
o.setEnabled(false);
contact.setEnabled(false);
mem_type.setEnabled(false);
addresstxt.setEnabled(false);
jdbc();
try
{
    String sql="Select * from member where username='"+Login.mname.getText()+"';";
    rs=stmt.executeQuery(sql);
    rs.next();
    nametxt.setText(rs.getString(2));
    email.setText(rs.getString(6));
    char gen=Character.toLowerCase(rs.getString(7).charAt(0));
    if(gen=='m')
        m.setSelected(true);
    else if(gen=='f')
        f.setSelected(true);
    else if(gen=='o')
        o.setSelected(true);
    contact.setText(rs.getString(4));
    addresstxt.setText(rs.getString(5));
    if(rs.getString(8).equals("P"))
        mem_type.setSelectedIndex(0);
    else if(rs.getString(8).equals("G"))
        mem_type.setSelectedIndex(1);
    else if(rs.getString(8).equals("S"))
        mem_type.setSelectedIndex(2);
    else if(rs.getString(8).equals("B"))
        mem_type.setSelectedIndex(3);
    /*if(rs.getString(5)!=null)
    pic.setIcon(new ImageIcon(""+rs.getString(5)+""));*/
    
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null, e.getMessage());
}
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new Member().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        logout();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
nametxt.setEnabled(true);
email.setEnabled(true);
m.setEnabled(true);
f.setEnabled(true);
o.setEnabled(true);
contact.setEnabled(true);
mem_type.setEnabled(true);
addresstxt.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_editActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String u=newname.getText();
String p1=new String(newpass.getPassword());
String p2=new String(confpass.getPassword());
if(p1.equals(p2))
{
    jdbc();
    try
    {
        //System.out.println(nametxt.getText());
        String sql="update member set username='"+u+"',pass='"+p1+"' where membername='"+nametxt.getText()+"';";  
        
        
        //System.out.println(sql);
        int i=stmt.executeUpdate(sql);
        if(i!=0)
        JOptionPane.showMessageDialog(rootPane,"Succesfully updated data!"); 
        newname.setText("");
        newpass.setText("");
        confpass.setText("");       
    }
    catch(Exception e)
    {
        JOptionPane.showMessageDialog(rootPane,e.getMessage());
    }
}
else
{
    JOptionPane.showMessageDialog(rootPane,"Passwords do not match"); 
}
    
    
    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void confActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confActionPerformed
String gen="";
if(m.isSelected())
    gen="M";
else if(f.isSelected())
    gen="F";
else if(o.isSelected())
    gen="O";
int index=mem_type.getSelectedIndex();
String type=null;
switch(index)
{
    case 0: type="P";
    break;
    case 1: type="G";
    break;
    case 2: type="S";
    break;
    case 3: type="B";
    break;
}
jdbc();
try
{
    String sql="update member set membername = '"+nametxt.getText()+"',email='"+email.getText()+"',gender='"+gen+"',contact='"+contact.getText()+"',address='"+addresstxt.getText()+"',membership='"+type+"' where username='"+Login.mname.getText()+"';";
   // System.out.println(sql);
    int i=stmt.executeUpdate(sql);
    if(i!=0)
    JOptionPane.showMessageDialog(rootPane,"Succesfully updated data!");   
    
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(rootPane,e.getMessage());
}
nametxt.setEnabled(false);
email.setEnabled(false);
m.setEnabled(false);
f.setEnabled(false);
o.setEnabled(false);
contact.setEnabled(false);
mem_type.setEnabled(false);
addresstxt.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_confActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminSettings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addresstxt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton conf;
    private javax.swing.JPasswordField confpass;
    private javax.swing.JTextField contact;
    private javax.swing.JButton edit;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton f;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton m;
    private javax.swing.JComboBox mem_type;
    private javax.swing.JTextField nametxt;
    private javax.swing.JTextField newname;
    private javax.swing.JPasswordField newpass;
    private javax.swing.JRadioButton o;
    // End of variables declaration//GEN-END:variables
}
