import javax.swing.table.*;
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ravik
 */
public class Member_Issue extends Global {
 public void jdbc()
{
    try
        {
            Class.forName("java.sql.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/lbms?useSSL=false","root","1234");
            stmt=con.createStatement();          
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error: "+e.getMessage());           
        }
}
    /**
     * Creates new form Preview
     */
    public Member_Issue() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        t1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        memid = new javax.swing.JTextField();
        memname = new javax.swing.JTextField();
        issuebtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        mgz = new javax.swing.JRadioButton();
        bk2 = new javax.swing.JRadioButton();
        bk3 = new javax.swing.JRadioButton();
        bk1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Issue Books");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, -1, -1));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/search.png"))); // NOI18N
        jLabel7.setText("Search by ID or Name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, -1, -1));

        search.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 16)); // NOI18N
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 330, 230, 30));

        t1.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 16)); // NOI18N
        t1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "<html><h3>Book Name</h3>", "<html><h3>Author</h3>", "<html><h3>Status</h3>"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        t1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(t1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 640, 110));

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Member ID ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, -1, 30));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Member Name");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, -1, -1));

        memid.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 16)); // NOI18N
        memid.setEnabled(false);
        memid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memidActionPerformed(evt);
            }
        });
        jPanel1.add(memid, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 210, 30));

        memname.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 16)); // NOI18N
        memname.setEnabled(false);
        jPanel1.add(memname, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 220, 210, 30));

        issuebtn.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        issuebtn.setText("ISSUE");
        issuebtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        issuebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issuebtnActionPerformed(evt);
            }
        });
        jPanel1.add(issuebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 640, 120, 40));

        jButton3.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/home.png"))); // NOI18N
        jButton3.setText("HOME");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jButton4.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/logout.png"))); // NOI18N
        jButton4.setText("LOGOUT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 60, -1, -1));

        buttonGroup1.add(mgz);
        mgz.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        mgz.setForeground(new java.awt.Color(255, 255, 255));
        mgz.setText("Magazine");
        mgz.setContentAreaFilled(false);
        jPanel1.add(mgz, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 550, -1, -1));

        buttonGroup1.add(bk2);
        bk2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        bk2.setForeground(new java.awt.Color(255, 255, 255));
        bk2.setText("Book 2");
        bk2.setContentAreaFilled(false);
        jPanel1.add(bk2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 550, -1, -1));

        buttonGroup1.add(bk3);
        bk3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        bk3.setForeground(new java.awt.Color(255, 255, 255));
        bk3.setText("Book 3");
        bk3.setContentAreaFilled(false);
        jPanel1.add(bk3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 550, -1, -1));

        buttonGroup1.add(bk1);
        bk1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        bk1.setForeground(new java.awt.Color(255, 255, 255));
        bk1.setText("Book 1");
        bk1.setContentAreaFilled(false);
        bk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bk1ActionPerformed(evt);
            }
        });
        jPanel1.add(bk1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 550, 90, 30));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 140)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/library.jpg"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
DefaultTableModel tm=(DefaultTableModel)t1.getModel();
tm.setRowCount(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowDeactivated

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
new Member().setVisible(true);
this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
logout();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void memidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memidActionPerformed

    }//GEN-LAST:event_memidActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
jdbc();
        String b = search.getText();
try
{
     String sql = "Select * from inventory where bookid = '"+b+"' or bookname like '"+b+"%';";
     //System.out.println(sql);
    rs = stmt.executeQuery(sql);
    DefaultTableModel tm=(DefaultTableModel)t1.getModel();
    tm.setRowCount(0);
    while(rs.next())
    {
        int avbl=rs.getInt(6);
        if(avbl!=0)
        {
        Object arr[]={rs.getString(2),rs.getString(3),"Available"};
        tm.addRow(arr);
        }
        else
        {
        Object arr[]={rs.getString(2),rs.getString(3),"Unavailable"};
        tm.addRow(arr);
        }
    }
}
catch(Exception e)
{
   JOptionPane.showMessageDialog(null,"Search Error: "+e.getMessage()); 
}
    }//GEN-LAST:event_searchActionPerformed

    private void issuebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issuebtnActionPerformed
jdbc();
try
{
    DefaultTableModel tm=(DefaultTableModel)t1.getModel();
    int i=t1.getSelectedRow();
    String s=(String) tm.getValueAt(i,0);
    String status=(String)tm.getValueAt(i, 2);
    if(status.equals("Unavailable"))
        JOptionPane.showMessageDialog(null, "This book is not available. Please select another book.");
    else
    {
    String option="";
    String mid=memid.getText();
    String qry="Select * from member where memberid='"+mid+"';";
    rs=stmt.executeQuery(qry);
    rs.next();
//Coding for inventory and member table
    if(bk1.isSelected())
    {
       option = "book1";
       String book1=rs.getString("book1");
    if(book1!=null)
    {
        JOptionPane.showMessageDialog(null, "Please return the existing book in this slot.");
    }
    else
    {
      String sql="update member set " +option+"='"+s+"' where memberid='"+mid+"';";
    stmt.executeUpdate(sql);
    String sql2="update inventory set available=available-1 where bookname"+"='"+s+"';";
    //System.out.println(sql2);
    stmt.executeUpdate(sql2);
    JOptionPane.showMessageDialog(null,"Book/Magazine has been issued!"); 
    search.setText("");
    }
    }
    else if(bk2.isSelected())
    {
      option = "book2";  
      String book2=rs.getString("book2");
    if(book2!=null)
    {
        JOptionPane.showMessageDialog(null, "Please return the existing book in this slot.");
    }
    else
    {
    String sql="update member set " +option+"='"+s+"' where memberid='"+mid+"';";
    stmt.executeUpdate(sql);
    String sql2="update inventory set available=available-1 where bookname"+"='"+s+"';";
    //System.out.println(sql2);
    stmt.executeUpdate(sql2);
    JOptionPane.showMessageDialog(null,"Book/Magazine has been issued!"); 
    search.setText("");
    }
    }
    else if(bk3.isSelected())
    {
      option = "book3";
      String book3=rs.getString("book3");
    if(book3!=null)
    {
        JOptionPane.showMessageDialog(null, "Please return the existing book in this slot.");
    }
    else
    {
        String sql="update member set " +option+"='"+s+"' where memberid='"+mid+"';";
    stmt.executeUpdate(sql);
    String sql2="update inventory set available=available-1 where bookname"+"='"+s+"';";
    //System.out.println(sql2);
    stmt.executeUpdate(sql2);
    JOptionPane.showMessageDialog(null,"Book/Magazine has been issued!");
    search.setText("");
    }
    }
    else if(mgz.isSelected())
    {
      option = "magazine";
      String mag=rs.getString("magazine");
    if(mag!=null)
    {
        JOptionPane.showMessageDialog(null, "Please return the existing book in this slot.");
    }
    else
    {
        String sql="update member set " +option+"='"+s+"' where memberid='"+mid+"';";
    stmt.executeUpdate(sql);
    String sql2="update inventory set available=available-1 where bookname"+"='"+s+"';";
    //System.out.println(sql2);
    stmt.executeUpdate(sql2);
    JOptionPane.showMessageDialog(null,"Book/Magazine has been issued!");
    search.setText("");
    }
    }    
    else
    JOptionPane.showMessageDialog(null,"Please select a book/magazine!");
//Coding for weekly summary table
    ResultSet rs2=stmt.executeQuery("select curdate();");
    rs2.next();
    String d=rs2.getString(1);
    ResultSet rs3=stmt.executeQuery("select * from inventory where bookname='"+s+"';");
    rs3.next();
    String bid=rs3.getString("bookid");
    String name=s;
    ResultSet rs4=stmt.executeQuery("Select * from member where memberid='"+mid+"';");
    rs4.next();
    String mname=rs4.getString("membername");
    String act="issued";             
    String sql="insert into summary values('"+d+"','"+bid+"','"+name+"','"+mid+"','"+mname+"','"+act+"');";
    stmt.executeUpdate(sql);
    }
}
catch(Exception e)
{
   JOptionPane.showMessageDialog(null, "Issue Error: "+e.getMessage()); 
}

        // TODO add your handling code here:
    }//GEN-LAST:event_issuebtnActionPerformed

    private void bk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bk1ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_bk1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
jdbc();
try
{
    rs=stmt.executeQuery("select memberid,membername,membership from member where username='"+Login.mname.getText()+"';");
    rs.next();
    memid.setText(rs.getString(1));
    memname.setText(rs.getString(2)); 
    String membtype = rs.getString(3);
                switch (membtype)
                {
                    case "G":
                        bk1.setEnabled(true);
                        bk2.setEnabled(true);
                        bk3.setEnabled(false);
                        mgz.setEnabled(true);
                        break;
                    case "S":
                        bk1.setEnabled(true);
                        bk2.setEnabled(true);
                        bk3.setEnabled(true);
                        mgz.setEnabled(false);
                        break;
                    case "B":
                        bk1.setEnabled(true);
                        bk2.setEnabled(true);
                        mgz.setEnabled(false);
                        bk3.setEnabled(false);
                        break;
                    default:
                        break;
                    case "P":
                        bk1.setEnabled(true);
                        bk2.setEnabled(true);
                        bk3.setEnabled(true);
                        mgz.setEnabled(true);
                        break;
                }
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(this, "Error: "+e.getMessage());
}
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Preview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Preview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Preview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Preview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Preview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bk1;
    private javax.swing.JRadioButton bk2;
    private javax.swing.JRadioButton bk3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton issuebtn;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField memid;
    private javax.swing.JTextField memname;
    private javax.swing.JRadioButton mgz;
    private javax.swing.JTextField search;
    private javax.swing.JTable t1;
    // End of variables declaration//GEN-END:variables
}
