
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ANIL BARBARE
 */
public class Member extends Global {
    public void jdbc()
{
    try
        {
            Class.forName("java.sql.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/lbms?useSSL=false","root","1234");
            stmt=con.createStatement();          
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error: "+e.getMessage());           
        }
}

    /**
     * Creates new form Admin
     */
    public Member() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        issuebtn = new javax.swing.JButton();
        settbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        retbtn = new javax.swing.JButton();
        advsearch1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Member Home");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, -1, -1));

        issuebtn.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        issuebtn.setForeground(new java.awt.Color(255, 255, 255));
        issuebtn.setText("ISSUE");
        issuebtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        issuebtn.setContentAreaFilled(false);
        issuebtn.setNextFocusableComponent(settbtn);
        issuebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issuebtnActionPerformed(evt);
            }
        });
        getContentPane().add(issuebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 210, 150));

        settbtn.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        settbtn.setForeground(new java.awt.Color(255, 255, 255));
        settbtn.setText(" SETTINGS");
        settbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        settbtn.setContentAreaFilled(false);
        settbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settbtnActionPerformed(evt);
            }
        });
        getContentPane().add(settbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 450, 210, 150));

        jButton1.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jButton1.setText("LOGOUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 70, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/default_profile.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 160, 160));

        user.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 16)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 160, 60));

        retbtn.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        retbtn.setForeground(new java.awt.Color(255, 255, 255));
        retbtn.setText("RETURN");
        retbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        retbtn.setContentAreaFilled(false);
        retbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retbtnActionPerformed(evt);
            }
        });
        getContentPane().add(retbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 210, 210, 150));

        advsearch1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        advsearch1.setForeground(new java.awt.Color(255, 255, 255));
        advsearch1.setText("<html>\n<center>\n<body>ADVANCED\n<br>SEARCH</center>");
        advsearch1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        advsearch1.setContentAreaFilled(false);
        advsearch1.setNextFocusableComponent(settbtn);
        advsearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advsearch1ActionPerformed(evt);
            }
        });
        getContentPane().add(advsearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, 210, 150));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/library.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void settbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settbtnActionPerformed
new MemberSettings().setVisible(true);
this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_settbtnActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
jdbc();
try
{
    rs=stmt.executeQuery("select membername from member where username='"+Login.mname.getText()+"';");
    rs.next();
    String name=rs.getString(1);
    user.setText("<html><body>"+name);
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(this, "Error: "+e.getMessage());
}
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
logout();
new Login().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void issuebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issuebtnActionPerformed
new Member_Issue().setVisible(true);
this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_issuebtnActionPerformed

    private void retbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retbtnActionPerformed
new Member_Return().setVisible(true);
this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_retbtnActionPerformed

    private void advsearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advsearch1ActionPerformed
new Advanced_Search().setVisible(true);
this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_advsearch1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton advsearch1;
    private javax.swing.JButton issuebtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton retbtn;
    private javax.swing.JButton settbtn;
    public static javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
