import java.sql.*;
import javax.swing.JOptionPane;
import javax.mail.Session;
import java.util.Properties;
import javax.mail.PasswordAuthentication;
import javax.mail.Authenticator;
/*


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DAV
 */
public class Orders extends EmailUtil {
    String order="";
     int a=0;
     public static int stat,stat1=0;
     public static void jdbc()
{
    try
        {
            Class.forName("java.sql.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/lbms","root","1234");
            stmt=con.createStatement();          
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error: "+e.getMessage());           
        }
}
    /**
     * Creates new form Orders
     */
    public Orders() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        qty = new javax.swing.JTextField();
        pub = new javax.swing.JTextField();
        bkname = new javax.swing.JTextField();
        author = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, 70, 30));
        jPanel1.add(pub, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 460, 30));
        jPanel1.add(bkname, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 460, 30));
        jPanel1.add(author, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 460, 30));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Author");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Publication");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, -1, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quantity");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, -1, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Book Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Book Name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, -1, -1));

        jButton1.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/confirm_order.jpg"))); // NOI18N
        jButton1.setText("Place Order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 530, -1, 70));

        jButton2.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jButton2.setText("Clear Order List");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 620, -1, 60));

        jButton4.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/logout.png"))); // NOI18N
        jButton4.setText("LOGOUT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 50, -1, -1));

        jButton3.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/home.png"))); // NOI18N
        jButton3.setText("HOME");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jLabel7.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Order");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, -1, -1));

        jButton5.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/plus.png"))); // NOI18N
        jButton5.setText("Add Item To Order List");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, 400, 70));

        jButton6.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/manage_order.png"))); // NOI18N
        jButton6.setText("Manage Orders");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 530, 280, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/library.jpg"))); // NOI18N
        jLabel1.setText(" ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        logout();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new Admin().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

       int m=JOptionPane.showConfirmDialog(null,"Your order details are as follows:- "+"\n"+order+"\n"+"Do you wish to place this order?");
switch(m)
{
    case 0:
        try
        {                   
            
            stmt.executeUpdate("drop table if exists ord2;");
            stmt.executeUpdate("create table ord2 as select * from orders;");
            ResultSet rs1=stmt.executeQuery("select count(*) from ord2");
            rs1.next();
            int n2=rs1.getInt(1);
            //System.out.println(n2);
            /*ResultSet rs2=stmt.executeQuery("select count(*) from ord2");
            rs2.next();*/           
            //stmt.executeUpdate("delete from orders where orderno >1;");
            int diff=n2-stat;
            stat+=diff;
            a=1;            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error e2: "+e.getMessage());  
        }
        
        String rec="bkhousexyz@gmail.com";
        final String sen="readersheavenlibrary@gmail.com";
        final String pass="lbms1234";
        String host="smtp.gmail.com";
        Properties prop=System.getProperties();
        prop.put("mail.smtp.host","smtp.gmail.com");
        prop.put("mail.smtp.port","587");
        prop.put("mail.smtp.auth","true");
        prop.put("mail.smtp.starttls.enable","true");
        Authenticator auth=new Authenticator(){
            protected PasswordAuthentication getPasswordAuthentication(){
                return new PasswordAuthentication(sen, pass);
            }
        };
        Session session = Session.getInstance(prop,auth);
        EmailUtil.sendEmail(session,rec,"Order from Readers' Heaven Book Library","Sir "+"\n"+"This email is to place an order for the following items:"+"\n"+order+"\n"+"We request you to send the order along with the bill at the earliest."+"\n"+"Regards"+"\n"+"Readers' Heaven Book Library");
        break;
    case -1 :
    case 1:
    case 2:JOptionPane.showMessageDialog(null,"Continue adding items to order list");
    break;
            
}        order="";



        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
jdbc();
        try{
    String item="Book Name : "+bkname.getText()+", Author : "+author.getText()+", Publication : "+pub.getText()+", Quantity : "+ qty.getText()+"\n";
    order+=item;
     
    rs=stmt.executeQuery("select orderno from orders;");
    rs.last();
    int i=rs.getInt("orderno"); 
    //System.out.println(i);
    i++;
    String sql="insert into orders values("+i+",'"+bkname.getText()+"','"+author.getText()+"','"+pub.getText()+"',"+Integer.parseInt(qty.getText())+");";
    stmt.executeUpdate(sql);
    JOptionPane.showMessageDialog(null,"Item added");
    bkname.setText("");
    author.setText("");
    pub.setText("");
    qty.setText(""); 
}
catch(Exception e)
{
 JOptionPane.showMessageDialog(null,"Error e3: "+e.getMessage());      
}


        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
jdbc();
try{
    String sql="delete from orders where orderno >"+stat+";";
    stmt.executeUpdate(sql);
    order="";
JOptionPane.showMessageDialog(null,"List cleared");
}
catch(Exception e)
{
 JOptionPane.showMessageDialog(null,"Error: "+e.getMessage());      
}

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
jdbc();
      
       int b= JOptionPane.showConfirmDialog(rootPane,"Do you wish to continue?"+"\n"+"If you haven't placed the order your list will be emptied");
              if(b==0&&a==1)
       {
             try
{
            /*stmt.executeUpdate("delete from orders where orderno >1;");
            stmt.executeUpdate("drop table if exists ord3;");
            stmt.executeUpdate("create table ord3 as select * from ord2 ;");*/
            this.dispose();
new Manage_Orders().setVisible(true);
order="";
            
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,"Error e2: "+e.getMessage());
}
order="";
       }
       else if(b==0&&a!=1)
       {
           try
           {
            //stmt.executeUpdate("delete from orders where orderno >1;");
               order="";
            stmt.executeUpdate("drop table if exists ord2;");
            stmt.executeUpdate("create table ord2 as select * from orders;");
            stmt.executeUpdate("delete from ord2;");
           }
           catch(Exception e)
                   {
                       JOptionPane.showMessageDialog(null,"Error e2: "+e.getMessage());
                   }
           this.dispose();
new Manage_Orders().setVisible(true);
order="";
       }
       
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
jdbc();
        try{              
    rs=stmt.executeQuery("select orderno from orders;");
    rs.last();   
    stat=rs.getInt("orderno");       
    //System.out.println(a);
}
catch(Exception e)
{
 JOptionPane.showMessageDialog(null,"Error e1: "+e.getMessage());      
}
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {       
                jdbc();
        try{              
    rs=stmt.executeQuery("select count(*) from orders;");
    rs.last();   
    stat=rs.getInt(1);       
    //System.out.println(a);
}
catch(Exception e)
{
 JOptionPane.showMessageDialog(null,"Error e1: "+e.getMessage());      
}
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Orders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField author;
    private javax.swing.JTextField bkname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField pub;
    private javax.swing.JTextField qty;
    // End of variables declaration//GEN-END:variables
}
