import java.sql.*;
import javax.swing.JOptionPane;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Register.java
 *
 * Created on Oct 9, 2018, 1:00:55 PM
 */

/**
 *
 * @author DAV
 */
public class Register extends Global {
 
    public void jdbc()
{
    try
        {
            Class.forName("java.sql.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/lbms?useSSL=false","root","1234");
            stmt=con.createStatement();          
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error: "+e.getMessage());           
        }
}
    /** Creates new form Register */
    public Register() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        mid = new javax.swing.JTextField();
        F = new javax.swing.JRadioButton();
        O = new javax.swing.JRadioButton();
        nametxt = new javax.swing.JTextField();
        agetxt = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addresstxt = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        M = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        memtype = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        regstr = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        meminfo = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 72)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mid.setEditable(false);
        mid.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 16)); // NOI18N
        mid.setEnabled(false);
        mid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midActionPerformed(evt);
            }
        });
        getContentPane().add(mid, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 260, 150, 30));

        buttonGroup1.add(F);
        F.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 20)); // NOI18N
        F.setForeground(new java.awt.Color(255, 255, 255));
        F.setText("Female");
        F.setContentAreaFilled(false);
        F.setNextFocusableComponent(O);
        getContentPane().add(F, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 650, -1, 30));

        buttonGroup1.add(O);
        O.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 20)); // NOI18N
        O.setForeground(new java.awt.Color(255, 255, 255));
        O.setText("Other");
        O.setContentAreaFilled(false);
        O.setName(""); // NOI18N
        O.setNextFocusableComponent(memtype);
        getContentPane().add(O, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 650, -1, 30));

        nametxt.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 16)); // NOI18N
        nametxt.setNextFocusableComponent(agetxt);
        getContentPane().add(nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 240, 30));

        agetxt.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 16)); // NOI18N
        agetxt.setNextFocusableComponent(contact);
        agetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agetxtActionPerformed(evt);
            }
        });
        getContentPane().add(agetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 240, 30));

        contact.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 16)); // NOI18N
        contact.setNextFocusableComponent(addresstxt);
        contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactActionPerformed(evt);
            }
        });
        getContentPane().add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 240, 30));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 60, 30));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Age");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 40, 30));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contact No.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 120, 30));

        email.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 16)); // NOI18N
        email.setNextFocusableComponent(M);
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 570, 240, 30));

        addresstxt.setColumns(20);
        addresstxt.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 16)); // NOI18N
        addresstxt.setRows(5);
        addresstxt.setNextFocusableComponent(email);
        jScrollPane1.setViewportView(addresstxt);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 240, 130));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Address");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 90, 40));

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 570, 60, 30));

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gender");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 650, 80, 30));

        buttonGroup1.add(M);
        M.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 20)); // NOI18N
        M.setForeground(new java.awt.Color(255, 255, 255));
        M.setText("Male");
        M.setContentAreaFilled(false);
        M.setNextFocusableComponent(F);
        getContentPane().add(M, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 650, -1, 30));

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Member ID");
        jLabel9.setName(""); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 270, 120, 20));

        memtype.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        memtype.setMaximumRowCount(4);
        memtype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "JRR Tolkien Platinum ", "Dan Brown Gold", "Agatha Christie Silver", "JK Rowling Bronze" }));
        memtype.setNextFocusableComponent(uname);
        memtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memtypeActionPerformed(evt);
            }
        });
        getContentPane().add(memtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 330, 270, 40));

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Membership");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, -1, 40));

        regstr.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        regstr.setText("REGISTER");
        regstr.setNextFocusableComponent(back);
        regstr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regstrActionPerformed(evt);
            }
        });
        getContentPane().add(regstr, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 540, 150, -1));

        back.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/back.png"))); // NOI18N
        back.setText("BACK");
        back.setNextFocusableComponent(nametxt);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 619, -1, 80));

        jLabel8.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText(" Member Registration");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 610, 60));

        meminfo.setForeground(new java.awt.Color(255, 255, 255));
        meminfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/information-icon.png"))); // NOI18N
        meminfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        meminfo.setNextFocusableComponent(regstr);
        meminfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meminfoActionPerformed(evt);
            }
        });
        getContentPane().add(meminfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 330, 40, 40));

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Username");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 380, 120, 50));

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Password");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 440, 110, 50));

        uname.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 16)); // NOI18N
        uname.setNextFocusableComponent(pass);
        getContentPane().add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 390, 260, 30));

        pass.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 16)); // NOI18N
        pass.setNextFocusableComponent(regstr);
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 450, 260, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/library.jpg"))); // NOI18N
        jLabel13.setNextFocusableComponent(contact);
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactActionPerformed

    private void midActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_midActionPerformed

    private void memtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memtypeActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
this.dispose();
new Login().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void agetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agetxtActionPerformed

    private void meminfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meminfoActionPerformed
new Membership_Type().setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_meminfoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
/*nametxt.setText("");
agetxt.setText("");
contact.setText("");
addresstxt.setText("");
email.setText("");*/
nametxt.requestFocus();
jdbc();
try
{
    String sql="Select * from member;";
    rs=stmt.executeQuery(sql);
    rs.last();
    int id=(Integer.parseInt(rs.getString(1).substring(2)))+1;
    mid.setText("RH"+id);
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null, e.getMessage());
}

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void regstrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regstrActionPerformed
jdbc();
   int type=memtype.getSelectedIndex();
    String mem_type=null;
    switch(type)
    {
        case 0: mem_type="P";
        break;
        case 1: mem_type="G";
        break;
        case 2: mem_type="S";
        break;
        case 3:mem_type="B";
        break;
    }
    String gen=null;
    if(M.isSelected())
        gen="M";
    else if(F.isSelected())
        gen="F";
    else if(O.isSelected())
        gen="O";
    else
    {
        JOptionPane.showMessageDialog(null, "Please select a gender."); 
        gen="";
    }
        switch(gen)
    {
        case "M":
        case "F":
        case "O":     
        {
            try
            {
    String password=new String(pass.getPassword());
    String sql="insert into member(memberid,membername,age,contact,address,email,gender,membership,username,pass) values('"+mid.getText()+"','"+nametxt.getText()+"','"+agetxt.getText()+"','"+contact.getText()+"','"+addresstxt.getText()+"','"+email.getText()+"','"+gen+"','"+mem_type+"','"+uname.getText()+"','"+password+"');";
    //System.out.println(sql);
    stmt.executeUpdate(sql);
    JOptionPane.showMessageDialog(null, "You are now a member! Please go back and log in using your username and password.");
    nametxt.setText("");
    agetxt.setText("");
    contact.setText("");
    addresstxt.setText("");
    email.setText("");
    uname.setText("");
    pass.setText("");
M.setSelected(false);
F.setSelected(false);
O.setSelected(false);
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            break;
        }
        
        default:break;
}

        
        // TODO add your handling code here:
    }//GEN-LAST:event_regstrActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton F;
    private javax.swing.JRadioButton M;
    private javax.swing.JRadioButton O;
    private javax.swing.JTextArea addresstxt;
    private javax.swing.JTextField agetxt;
    private javax.swing.JButton back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton meminfo;
    private javax.swing.JComboBox memtype;
    private javax.swing.JTextField mid;
    private javax.swing.JTextField nametxt;
    private javax.swing.JPasswordField pass;
    private javax.swing.JButton regstr;
    private javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables

}
